local colors = {
    background = "#2e3233",
    ansi = {
      black   = "#242727",
      red     = "#eb7a73",
      green   = "#b9c675",
      yellow  = "#e8b267",
      blue    = "#8dbba3",
      magenta = "#e396a4",
      cyan    = "#99c792",
      white   = "#f1e4c2",
      grey    = "#5d5d5d",
      orange  = "#e89a5e",
    },
    brights = {
      black   = "#242727",
      red     = "#eb7a73",
      green   = "#b9c675",
      yellow  = "#e8b267",
      blue    = "#8dbba3",
      magenta = "#e396a4",
      cyan    = "#99c792",
      white   = "#f1e4c2",
      grey    = "#5d5d5d",
      orange  = "#e89a5e",
    }
}

return {
  tab_bar = {
    background = colors.background,
    active_tab = {
      bg_color = colors.background,
      fg_color = colors.ansi.white,
      intensity = "Bold",
      italic = false,
      strikethrough = false,
    },
    inactive_tab = {
      bg_color = colors.background,
      fg_color = colors.brights.grey,
      intensity = "Normal",
      underline = "None",
      italic = false,
      strikethrough = false,
    },
    inactive_tab_hover = {
      bg_color = colors.background,
      fg_color = colors.ansi.white,
      intensity = "Normal",
      underline = "None",
      italic = false,
      strikethrough = false,
    },
    new_tab = {
      bg_color = colors.background,
      fg_color = colors.ansi.grey,
      intensity = "Normal",
      underline = "None",
      italic = false,
      strikethrough = false,
    },
  },
  background = colors.background,
  foreground = colors.ansi.white,
  cursor_bg = colors.ansi.orange,
  cursor_fg = colors.background,
  selection_bg = colors.ansi.grey,
  selection_fg = colors.ansi.white,
  ansi = {
    colors.ansi.black,
    colors.ansi.red,
    colors.ansi.green,
    colors.ansi.yellow,
    colors.ansi.blue,
    colors.ansi.magenta,
    colors.ansi.cyan,
    colors.ansi.white,
  },
  brights = {
    colors.brights.black,
    colors.brights.red,
    colors.brights.green,
    colors.brights.yellow,
    colors.brights.blue,
    colors.brights.magenta,
    colors.brights.cyan,
    colors.brights.white,
  }
}
